name: Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
      - name: Install pnpm
        run: npm i pnpm -g
      - name: Install dependencies and build
        run: |
          pnpm i
          pnpm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: set -x ; cd ${{ secrets.PROJECT_PATH }} && pc git pull && pnpm i && pnpm run build && pm2 restart book-collab

