name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
      - name: Install pnpm
        run: npm i pnpm -g
      - name: Install dependencies and build
        run: |
          pnpm i
          pnpm run build

